---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: devopsgram
  namespace: devopsgram-dev
spec:
  image: felipeacezar/devopsgram
  interval: 5m
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: devopsgram
  namespace: devopsgram-dev
spec:
  imageRepositoryRef:
    name: devopsgram
    namespace: devopsgram-dev
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: devopsgram
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system  
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: develop
  update:
    path: ./k8s/clusters/dev