apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devopsgram-prod
resources:
  - ../base
  - namespace.yaml
patches:
- target:
    kind: Deployment
    name: devopsgram
  path: deployment-patch.yaml
- target:
    kind: Service
    name: devopsgram-service
  path: service-patch.yaml