name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Altere conforme necessário para a sua branch principal
  workflow_dispatch:  # Adiciona a capacidade de execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKER_HUB_USERNAME}}
          password: ${{env.DOCKER_HUB_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felipeacezar/devopsgram:latest
          build-args: NO_CACHE=true

  deploy:
    runs-on: ubuntu-latest
    container:
      image: quay.io/openshift/origin-cli:4.10
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to OpenShift
        env:
          OPENSHIFT_TOKEN: ${{env.OPENSHIFT_TOKEN}}
          OPENSHIFT_SERVER: ${{env.OPENSHIFT_SERVER}}
        run: |
          oc login --token=${OPENSHIFT_TOKEN} --server=${OPENSHIFT_SERVER} --insecure-skip-tls-verify=true

      - name: Switch to OpenShift project
        run: oc project ${{env.OPENSHIFT_PROJECT}}

      - name: Apply manifests
        run: |
          oc delete -f ocp/ --ignore-not-found=true || true
          oc apply -f ocp/ || { echo "Falha ao aplicar manifests"; exit 1; }

      - name: Restart deployment
        run: |
          oc get deployment/devopsgram && oc rollout restart deployment/devopsgram || echo "Deployment não encontrado, pulando restart."

      - name: Check rollout status
        run: oc rollout status deployment/devopsgram
